# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-20 22:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='gengyuns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(help_text='\u5f00\u57a6\u8352\u5730', max_length=255, verbose_name='\u8015\u8018')),
                ('text', models.TextField(blank=True, verbose_name='\u8352\u5730\u63cf\u8ff0')),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(help_text='\u7528\u6237\u7ed1\u5b9a', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
        ),
        migrations.CreateModel(
            name='zhishidian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=255, verbose_name='\u4e3b\u9898')),
                ('text', models.TextField(verbose_name='\u77e5\u8bc6\u70b9\u5185\u5bb9')),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='zhongzi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=255, verbose_name='\u64ad\u79cd')),
                ('text', models.TextField(verbose_name='\u79cd\u5b50\u63cf\u8ff0')),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('gengyuns_id', models.ForeignKey(help_text='\u7ed1\u5b9a\u8352\u5730', on_delete=django.db.models.deletion.CASCADE, to='gengyun.gengyuns', verbose_name='\u8015\u8018')),
                ('user_id', models.ForeignKey(help_text='\u7528\u6237\u7ed1\u5b9a', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
        ),
        migrations.AddField(
            model_name='zhishidian',
            name='zhongzi_id',
            field=models.ForeignKey(help_text='\u5173\u8054\u4e8c\u7ea7\u6807\u9898', on_delete=django.db.models.deletion.CASCADE, to='gengyun.zhongzi', verbose_name='\u4e8c\u7ea7\u4e3b\u9898'),
        ),
    ]
